name: Make PDF
on: [push]
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compilation
        uses: ./.github/actions/latexmk-action
      - name: Upload Document
        uses: actions/upload-artifact@v3
        with:
          name: talk
          path: talk.pdf
          if-no-files-found: error
